OrganizationName: <OrganizationName>
PersonalAccessToken: <PersonalAccessToken>
ProjectName: <ProjectName>
AgentPoolName: DSC
BuildAgents:
  UserName: worker
  Password: <Password>
  AzureLocation: West Europe
  AzureRoleSize: Standard_D4ls_v5
