OrganizationName: <OrganizationName>
PersonalAccessToken: <PersonalAccessToken>
ProjectName: <ProjectName>
AgentPoolName: <AgentPoolName>
NumbertOfBuildAgents: 4
BuildAgents:
  UserName: worker
  Password: <Password>
  AzureLocation: West Europe
  AzureRoleSize: Standard_D4ds_v6
