#- cAADAdministrativeUnit
- cAADNamedLocationPolicy
#- cAADConditionalAccessPolicy #Requires Microsoft Entra ID Premium
- cAADGroup
- cAADAuthorizationPolicy
- cAADGroupsSettings
- cAADSecurityDefaults
