ConditionalAccessPolicy: AllowFullAccess
Ensure: Present
DisallowInfectedFileDownload: True
DisplayStartASiteOption: True
EmailAttestationReAuthDays: 30
EmailAttestationRequired: False
ExternalServicesEnabled: True
IPAddressEnforcement: False
IPAddressWACTokenLifetime: 15
IsSingleInstance: Yes
TenantId: '[x={ $azBuildParameters."$($Node.Environment)".AzTenantName }=]'
CertificateThumbprint: '[x={ ($azBuildParameters."$($Node.Environment)".Identities | Where-Object Name -eq M365DscLcmApplication).CertificateThumbprint }=]'
ApplicationId: '[x={ ($azBuildParameters."$($Node.Environment)".Identities | Where-Object Name -eq M365DscLcmApplication).ApplicationId }=]'
