trigger: none

pool:
  vmImage: windows-latest

variables:
  buildFolderName: output
  testResultFolderName: testResults
  defaultBranch: main
  Agent.Source.Git.ShallowFetchDepth: 0

parameters:
  - name: buildEnvironments
    type: object
    default:
      - Name: Dev
      - Name: Test
      - Name: Prod
  - name: poolName
    type: string
    default: DSC

stages:

  - template: exportDscTemplate.yml
    parameters:
      buildEnvironments: ${{ parameters.buildEnvironments }}
      poolName: ${{ parameters.poolName }}
