trigger: none

pool:
  vmImage: windows-latest

variables:
  buildFolderName: output
  testResultFolderName: testResults
  defaultBranch: main
  Agent.Source.Git.ShallowFetchDepth: 0

parameters:
  - name: buildEnvironments
    type: object
    default:
      - Name: Dev
      - Name: Test
        DependsOn: Dev
      - Name: Prod
        DependsOn: Test
  - name: poolName
    type: string
    default: DSC

stages:

  - template: initTemplate.yml
    parameters:
      buildEnvironments: ${{ parameters.buildEnvironments }}
      poolName: ${{ parameters.poolName }}

  - template: startExistingDscTemplate.yml
    parameters:
      buildEnvironments: ${{ parameters.buildEnvironments }}
      poolName: ${{ parameters.poolName }}

  - template: testDscTemplate.yml
    parameters:
      buildEnvironments: ${{ parameters.buildEnvironments }}
      poolName: ${{ parameters.poolName }}
